name: Lint Markdown Files

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint-md:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run lint-md
    - name: Run lint-md
      run: npx lint-md .
