name: Merge to Docs Branch

on:
  push:
    branches:
      - develop

jobs:
  merge-to-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Merge to Docs Branch
      run: |
        git config user.name "andsonder"
        git config user.email "changlu@keter.top"
        
        git checkout docs
        git merge develop --no-edit
        git push origin docs
