name: Merge to Docs Branch

on:
  push:
    branches:
      - develop

jobs:
  merge-to-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Merge to Docs Branch
      run: |
        git config user.name "andsonder"
        git config user.email "changlu@keter.top"
        git config pull.rebase false

        git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/PaddleJitLab/CUDATutorial.git
        cd CUDATutorial
        git fetch --all
        
        git checkout -b docs origin/docs
        git pull origin develop
        git push origin docs
