name: Merge to Docs Branch

on:
  push:
    branches:
      - develop

jobs:
  merge-to-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Merge to Docs Branch
      run: |
        git config user.name "andsonder"
        git config user.email "changlu@keter.top"
        
        git remote add origin_with_token https://${{ secrets.GITHUB_TOKEN }}@github.com/PaddleJitLab/CUDATutorial.git
        git fetch origin_with_token
        
        git checkout -- docs
        git pull origin_with_token develop
        git push origin_with_token docs
